targets:
  $default:
    builders:
      # Configure the builder `pkg_name|builder_name`
      # In this case, the member_count builder defined in `../example`
      dart_eval_generator|member_count:
        generate_for:
          - lib/*.dart