name: Check for lints

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Flutter Action
        uses: subosito/flutter-action@v2
      - name: Install Package Dependencies
        run: flutter packages get
      - name: Get dependencies for example
        run: flutter pub get
        working-directory: example
      - name: Lint using flutter analyze
        run: flutter analyze .